apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  labels:
    service: connect
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: connect
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        service: connect
    spec:
      hostname: connect
      restartPolicy: Always
      enableServiceLinks: false
      containers:
        - name: connect
          image: confluentinc/cp-kafka-connect-base:7.2.2
          ports:
            - containerPort: 30083
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.8.1"]
          env:
            - name: CLASSPATH
              value: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.3.0.jar
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: kafka:29092
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: docker-connect-configs
            - name: CONNECT_CONSUMER_INTERCEPTOR_CLASSES
              value: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
            - name: CONNECT_GROUP_ID
              value: compose-connect-group
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_LOG4J_LOGGERS
              value: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
            - name: CONNECT_OFFSET_FLUSH_INTERVAL_MS
              value: "10000"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: docker-connect-offsets
            - name: CONNECT_PLUGIN_PATH
              value: /usr/share/java,/usr/share/confluent-hub-components
            - name: CONNECT_PRODUCER_INTERCEPTOR_CLASSES
              value: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: connect
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: docker-connect-status
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.storage.StringConverter