version: '3.7'
services:
  nbsadapter:
    image: raddanki64/eqartifacts:nbsadapter
    ports:
      - "8080:8080"
    networks:
      - apps_network
    volumes:
      - /tmp/hl7files:/tmp/hl7files

  phinadapter:
    image: raddanki64/eqartifacts:phinadapter
    ports:
      - "8090:8090"
    networks:
      - apps_network

networks:
  apps_network:
      external:
        name: adapter_network



