#!/bin/ksh

echo "Setting up vault"
VAULT_ADDR=http://localhost:8200
VAULT_TOKEN=nj101
export VAULT_ADDR VAULT_TOKEN

curl $VAULT_ADDR/v1/secrets/nbsadapter/local -d @nbsadapter.local.json -H "X-Vault-Token: nj101" -X POST
curl $VAULT_ADDR/v1/secrets/nbsadapter/local -H "X-Vault-Token: nj101" -X GET

curl $VAULT_ADDR/v1/secrets/phinadapter/local -d @phinadapter.local.json -H "X-Vault-Token: nj101" -X POST
curl $VAULT_ADDR/v1/secrets/phinadapter/local -H "X-Vault-Token: nj101" -X GET

curl $VAULT_ADDR/v1/secrets/jwtgenerator/local -d @jwtgenerator.local.json -H "X-Vault-Token: nj101" -X POST
curl $VAULT_ADDR/v1/secrets/jwtgenerator/local -H "X-Vault-Token: nj101" -X GET

if [ ! -d "/tmp/hl7files" ] 
then
    mkdir /tmp/hl7files
    echo "Created directory /tmp/hl7files"
fi

