spring:
  application:
    name: nbsadapter

logging:
  file: logs/nbsadapter.log
  
  pattern:
    console: "%d %-5level %logger : %file-%line : %msg%n"
    file:    "%d %-5level [%thread] %logger : [ramesh] : %msg%n"
    
  level:
    com.apps.restfulApp.api.controller: ERROR

---
spring:
  profiles: development
  
  datasource:
    driver-class-name: vault_nbsdb_driver_class_name
    url: vault_nbsdb_url
    username: vault_nbsdb_username
    password: vault_nbsdb_password

mongo:
    url: vault_mongo_url
    dbname: vault_mongo_dbname

report-stream:
  hl7-files-dir-url: vault_hl7_files_directory

kafka:
  outbound:
    hl7-messages-endpoint: vault_hl7_messages_endpoint
    xml-messages-endpoint: vault_xml_messages_endpoint

hashivault:
  authendpoint:    http://host.docker.internal:8200/v1/auth/cert/login
  secretsendpoint: http://host.docker.internal:8200/v1/secrets/${spring.application.name}/${spring.profiles.active}
  encryptendpoint: http://host.docker.internal:8200/v1/transit/encrypt/msg-key
    
thread-pooling:
  core-pool-size: 25
  max-pool-size: 300

server:
  tomcat:
    accept-count: 100
    max-connections: 10000
    max-threads: 200
