spring:
  application:
    name: nbsauthenticator

logging:
  pattern:
    console: "%d %-5level %logger : %file-%line : %msg%n"
    file:    "%d %-5level [%thread] %logger : [ramesh] : %msg%n"
    
  level:
    com.apps.restfulApp.api.controller: ERROR

---
spring:
  config:
    active:
      on-profile: default

  datasource:
    nbsclassic:
      url: jdbc:sqlserver://${DI_NBS_DBSERVER};databaseName=${DI_NBS_DBNAME};encrypt=true;trustServerCertificate=true;
      username: ${DI_NBS_DBUSER}
      password: ${DI_NBS_DBPASSWORD}
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

auth:
  provider: ${AUTH_FACTORY}

  nbsclassic:
    secretforalgorithm: ${AUTH_SECRET}

  keycloak:
    url: ${KEYCLOAK_URL}
    infourl: ${KEYCLOAK_INFOURL}
    clientid: ${KEYCLOAK_CLIENT_ID}
    clientsecret: ${KEYCLOAK_CLIENT_SECRET}








